export const SET_ERROR = 'SET_ERROR';

export const LOADING_ALL_BALANCES = 'LOADING_ALL_BALANCES';
export const GET_ALL_BALANCES = 'GET_ALL_BALANCES';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';